### ISSUE TITLE
为啥会出现这个问题 我pip也没法解决

### ISSUE THREAD

**Issue by kingchun** [jwansek/autoLogger#2]
[root@vultr autoLogger]# python3 autoLogger.py 
Traceback (most recent call last):
  File "autoLogger.py", line 3, in <module>
    import database
  File "/root/autoLogger/database.py", line 1, in <module>
    import autoLogger
  File "/root/autoLogger/autoLogger.py", line 7, in <module>
    workingdir = sys.argv[1]
IndexError: list index out of range

**Comment by jwansek** [comment]
You need to include the path to the config files etc as an argument. For example:

`python3 /home/eden/autoLogger/autoLogger.py /home/eden/autoLogger/`

**Comment by kingchun** [comment]
谢谢哦老哥 我懂了
